### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by MaybeHarmless** [dplochcoder/HollowKnight.MoreDoors#10]
When I have the setting to enable this in vanilla, which is what I wanted to do it with, the game won't start, rather the menu will disappear as if it was about to fade to black but it does not, and it just sits on the background screen. Was pretty interested in trying this out so if a fix could be applied I'd very much like to hear about it.

**Comment by dplochcoder** [comment]
Most likely you're missing a required dependency. Can you upload your Modlog.txt from the failed attempt?

**Comment by MaybeHarmless** [comment]
[ModLog.txt](https://github.com/dplochcoder/HollowKnight.MoreDoors/files/14394412/ModLog.txt)
Is this it?

**Comment by dplochcoder** [comment]
That's the right file but I don't see any errors, you need to copy it after you attempt to start the MoreDoors save

**Comment by MaybeHarmless** [comment]
[ModLog.txt](https://github.com/dplochcoder/HollowKnight.MoreDoors/files/14394737/ModLog.txt)
Alright how bout now?

**Comment by dplochcoder** [comment]
It looks the same, I still don't see any error messages relevant to MoreDoors, just a bunch of logging spam from CustomKnight.  You might want to reach out for help on the modding server

**Comment by MaybeHarmless** [comment]
Ill do that, thanks for the attempt at least.

**Comment by dplochcoder** [comment]
Closing as won't fix for now, can't do much without more info

**Comment by dplochcoder** [comment]
Closing
