### ISSUE TITLE
Strange behavior with Lore Master Mod

### ISSUE THREAD

**Issue by JSzwast** [dplochcoder/HollowKnight.MoreDoors#8]
While playing randomizer with Lore Master, if Listening ability is randomized, you can't interact with new doors at all, just like they were treated as npcs. Not sure if the problem is in your mod though, and if you have intention to try to fix it, but I thought you would like to know anyway.

Thanks!

**Comment by dplochcoder** [comment]
I don't know the specific commit but I believe this has been resolved on the Lore Master side
